### ISSUE TITLE
Integrate existing driver for wireless chip

### ISSUE THREAD

**Issue by steup** [steup/contiki#7]
Review At86rf231/At86rf232 implementation in Contiki
Change necessary parameters SPI-Pins, Chip-IDs

**Comment by viererbe** [comment]
- use of existing SPI Parameters from the rf framework for the device at86rf232 (pal_board.c)
- general integration of the rf stack (pal / tal / mac)
  => wireless communication without contiki
- contiki interface implementation
  => ToDo: test with contiki app

**Comment by viererbe** [comment]
contiki interface implementation closed, tested with MAC broadcast
